ReferenceError: sessionStorage is not defined fix (#60)
* ReferenceError: sessionStorage is not defined fix

* ReferenceError: sessionStorage is not defined - one line rewrite

(cherry picked from commit 4369855)